name: Deploy Cloudflare Pages (ordered)

on:
  # Pages だけの変更ならこれで発火
  push:
    branches: ['**']                           # 必要なら ['main'] に
    paths:
      - 'public/**'
      - 'functions/**'
      - '.github/workflows/deploy-pages.yaml'
  # DO が完了したら自動実行（順番保証用）
  workflow_run:
    workflows: ["Deploy DO Worker"]            # 上のファイル名に一致させる
    types: [completed]

jobs:
  deploy:
    # DO 成功時のみ実行。push なら無条件。
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    runs-on: ubuntu-latest
    permissions:
      contents: read

    # 同じブランチの Pages デプロイは直列化して競合回避
    concurrency:
      group: pages-${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      # push で DO も同時に変更されている場合はスキップ（順序のため）
      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            pages:
              - 'public/**'
              - 'functions/**'
            do:
              - 'workers/do-worker/**'

      - name: Determine target branch
        id: branch
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "name=${{ github.event.workflow_run.head_branch }}" >> "$GITHUB_OUTPUT"
          else
            echo "name=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi

      # push イベント時：Pages 変更はあるが DO 変更はない → 実行
      # workflow_run イベント時：DO 成功後 → 実行
      - name: Deploy Pages
        if: |
          (github.event_name == 'push' && steps.changes.outputs.pages == 'true' && steps.changes.outputs.do != 'true')
          || (github.event_name == 'workflow_run')
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            pages deploy ./public
            --project-name ${{ secrets.CF_PAGES_PROJECT }}
            --branch ${{ steps.branch.outputs.name }}