name: Deploy Cloudflare Pages (public + functions)

on:
  push:
    branches: [ main ]
    paths:
      - 'public/**'
      - 'functions/**'
      - '.github/workflows/deploy-pages.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # npx wrangler を使うので Node は必要（インストールは不要）
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          check-latest: true

      - name: Deploy to Cloudflare Pages
        run: npx wrangler@latest pages deploy ./public \
              --project-name "${{ secrets.CF_PAGES_PROJECT }}" \
              --branch "${{ github.ref_name }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}